In [2]:
import numpy as np
import pandas as pd

data = pd.read_json('data.json')
# df = pd.DataFrame(data)

# data

In [3]:
df = pd.DataFrame(data)
# Web scrap all the links of the cities and after that get all the restraunts chians and then match their ratings_number in their cities


In [22]:
# We'll access restaurants and do a function on each object and replace it
ratingCountSet = set([])
df = pd.DataFrame(data)
ratings_array = []
cnt = 0
ratingCountSet = set([])
def expenses(val):
    global cnt
    if(type(val) == float) :
        return np.nan
    for rest in val: 
        try:
            if(cnt == 0):
                print(val[rest]['rating_count'])
            # print('h')
            ratingCountSet.add(val[rest]['rating_count'])
        except:
            continue
    if(cnt == 0) :
        print(val)
    cnt = cnt+1
    return val
    obj = val
    cost = 0
    cnt = 0
    if(type(obj) == float):
        # NaN value preprocessed
        return 0
    
    if('rating' in obj):
        lc_obj = {"name" : obj['name'], "rating": 0 , "address" : "Not in data"}
        try:
            lc_obj['rating'] = float(obj['rating'])
            cnt = cnt+1
            ratings_array.append(lc_obj)
            
        except:
            lc_obj = lc_obj
        
        try:
            lc_obj['address'] = obj['address']
        except:
            lc_obj = lc_obj
        
        return lc_obj
    else:
       return np.nan
        
    
# 11 problem 
df2 = df
# print(df2)
# # print(df2)
# # print(df2)
df2 = df2.iloc[1]
# print(df2)
# print(df2)
# print(df3)
df3 = pd.DataFrame(df2)
# print(df3)

# df4 = df3['Pune'].apply(expenses)
df5 = df3.transpose()
# print(df5)
df5 = df5.iloc[0].apply(expenses)

Too Few Ratings
50+ ratings
100+ ratings
20+ ratings
Too Few Ratings
20+ ratings
100+ ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
50+ ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
100+ ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
Too Few Ratings
20+ ratings
Too Few Ratings
20+ ratings
Too Few Ratings
{'567335': {'name': 'AB FOODS POINT', 'rating': '

In [13]:

print(list(ratingCountSet))

['50+ ratings', 'NA', '5K+ ratings', 'Too Few Ratings', '1K+ ratings', '100+ ratings', '10K+ ratings', '20+ ratings', '500+ ratings']


In [14]:
ratingCountSet.remove('NA')
ratingCountSet.remove('Too Few Ratings')
dict = {key : int(key.split()[0].replace('+','').replace('K','000')) for key in list(ratingCountSet)}
dict

{'50+ ratings': 50,
 '5K+ ratings': 5000,
 '1K+ ratings': 1000,
 '100+ ratings': 100,
 '10K+ ratings': 10000,
 '20+ ratings': 20,
 '500+ ratings': 500}

In [15]:
dict['NA'] = np.nan
dict['Too Few Ratings'] = 2
dict

{'50+ ratings': 50,
 '5K+ ratings': 5000,
 '1K+ ratings': 1000,
 '100+ ratings': 100,
 '10K+ ratings': 10000,
 '20+ ratings': 20,
 '500+ ratings': 500,
 'NA': nan,
 'Too Few Ratings': 2}

In [26]:
# We'll access restaurants and do a function on each object and replace it
df = pd.DataFrame(data)
noOfReviews = []
cnt = 0
def expenses(val):
    global cnt
    if(type(val) == float):
        return np.nan
    
    # val = dict[val]
    obj = val
    
    cnt = cnt+1
    # print(cnt)
    max_lc_obj = {}
    mx = 0
    for ele in obj:
        lc_obj = {}
        try:
            lc_obj = {"name" : obj[ele]['name'], "rating_count": 0 , "address" : "Not in data"}
        except:
            # print(obj)
            continue
        try:
            if(dict[obj[ele]['rating_count']] >= mx):
                 mx = dict[obj[ele]['rating_count']]
                 max_lc_obj = lc_obj
            lc_obj['rating_count'] = dict[obj[ele]['rating_count']]
            
            noOfReviews.append(lc_obj)
            
        except:
            lc_obj = lc_obj
        
        try:
            lc_obj['address'] = obj[ele]['address']
        except:
            lc_obj = lc_obj
        
    if(len(max_lc_obj) == 0) :
         return np.nan
    return max_lc_obj

df6 = pd.DataFrame(df5)  
df7 = df6.transpose()
print(df7)
df7.iloc[0].apply(expenses)


                                                        Abohar   
restaurants  {'567335': {'name': 'AB FOODS POINT', 'rating'...  \

                                                      Adilabad   
restaurants  {'224008': {'name': 'Sharma Bakery', 'rating':...  \

                                                     Adityapur   
restaurants  {'321587': {'name': 'Kwality Walls Frozen Dess...  \

                                                         Adoni   
restaurants  {'146227': {'name': 'KKFC', 'rating': '3.8', '...  \

                                                      Agartala   
restaurants  {'227061': {'name': 'Gujrat Hotel and Restaura...  \

                                                          Agra Ahmedabad   
restaurants  {'74562': {'name': 'Bhagat Halwai (Dayal Bagh)...       NaN  \

                                                    Ahmednagar   
restaurants  {'245744': {'name': 'Noodles Bar Family Restau...  \

                                                 

Abohar          {'name': 'NIKKU VEG THALI', 'rating_count': 10...
Adilabad        {'name': 'Hotel Surabhi Grand', 'rating_count'...
Adityapur       {'name': 'QUEST REGENCY', 'rating_count': 1000...
Adoni           {'name': 'Biryani's' N' More', 'rating_count':...
Agartala        {'name': 'Sparks- The food hub', 'rating_count...
                                      ...                        
Wardha          {'name': 'FOOD FEAST RESTAURANTS', 'rating_cou...
Washim          {'name': 'Hotel Maniprabha', 'rating_count': 1...
Wayanad                                                       NaN
Yamuna-nagar    {'name': 'Sonu Sweet House', 'rating_count': 5...
Yavatmal        {'name': 'Satkar Dinning Hall', 'rating_count'...
Name: restaurants, Length: 623, dtype: object

In [27]:
noOfReviews

[{'name': 'AB FOODS POINT',
  'rating_count': 2,
  'address': 'AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINIC , NEAR IDBI BANK, ABOHAR'},
 {'name': 'Janta Sweet House',
  'rating_count': 50,
  'address': 'Janta Sweet House, Bazar No.9, Circullar Road, Abohar'},
 {'name': 'theka coffee desi',
  'rating_count': 100,
  'address': 'theka coffee desi, sahtiya sadan road city'},
 {'name': 'Singh Hut',
  'rating_count': 20,
  'address': 'Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR'},
 {'name': 'GRILL MASTERS',
  'rating_count': 2,
  'address': 'GRILL MASTERS, ADA Heights, Abohar - Hanumangarh Rd, Raipura, Abohar, Punjab 152116, India'},
 {'name': 'Sam Uncle',
  'rating_count': 20,
  'address': 'Sam Uncle, hanumangarh road near raja bajaj showroom abohar'},
 {'name': 'shere punjab veg',
  'rating_count': 100,
  'address': 'shere punjab veg, major surinder chowk near verma sons petrol pump and lic building abohar'},
 {'name': 'Shri Balaji Vaishno Dhaba',
  'rating_count': 2,
  'address': '

In [28]:
df_reviews = pd.DataFrame(noOfReviews)
print(df_reviews)

                           name  rating_count   
0                AB FOODS POINT           2.0  \
1             Janta Sweet House          50.0   
2             theka coffee desi         100.0   
3                     Singh Hut          20.0   
4                 GRILL MASTERS           2.0   
...                         ...           ...   
52577          The Food Delight           2.0   
52578  MAITRI FOODS & BEVERAGES           2.0   
52579           Cafe Bella Ciao           2.0   
52580               GRILL ZILLA           2.0   
52581            Lazeez kitchen           2.0   

                                                 address  
0      AB FOODS POINT, NEAR RISHI NARANG DENTAL CLINI...  
1      Janta Sweet House, Bazar No.9, Circullar Road,...  
2             theka coffee desi, sahtiya sadan road city  
3        Singh Hut, CIRCULAR ROAD NEAR NEHRU PARK ABOHAR  
4      GRILL MASTERS, ADA Heights, Abohar - Hanumanga...  
...                                                  ... 

In [29]:
df_reviews = df_reviews.sort_values(by = 'rating_count',ascending=False)

In [30]:

df_reviews[:10]

name  rating_count   
52050                             Mehfil       10000.0  \
52051                        Grand Hotel       10000.0   
48135                      DINE @ KUMARS        5000.0   
38541                        Sargam Food        5000.0   
50516                        Apna Sweets        5000.0   
22380  Mughal Darbar Chinese Chicken Hub        5000.0   
35797           Sujata Family Restaurant        5000.0   
30519                        Sargam Food        5000.0   
8872          Bhaina Hotel And Fast Food        5000.0   
50852                           Capsicum        5000.0   

                                                 address  
52050  Mehfil, Near Narayanguda Flyover, Narayanguda,...  
52051  Grand Hotel, Opposite Big Bazaar, 4-1-395,Abid...  
48135  DINE @ KUMARS, 71/ 3112-3 KILLIPPALAM THIRUVAN...  
38541  Sargam Food, Ground floor, Bilkha plaza, Kastu...  
50516  Apna Sweets, 37/7, Sethi Nagar, Ujjain, Madhya...  
22380  Mughal Darbar Chinese Chicken Hub, Opposite Ar...  
35797  Sujata Family Restaurant, Hotel Mayur, Fraser ...  
30519  Sargam Food, Ground floor, Bilkha plaza, Kastu...  
8872   Bhaina Hotel And Fast Food, Unit 4  , in front...  
50852  Capsicum, Pandit Madan Mohan Malviya Road, Sak...

Top 5 most popular restaurant chains in India?

Mehfil	10000.0	Mehfil, Near Narayanguda Flyover, Narayanguda,...

Grand Hotel	10000.0	Grand Hotel, Opposite Big Bazaar, 4-1-395,Abid...

DINE @ KUMARS	5000.0	DINE @ KUMARS, 71/ 3112-3 KILLIPPALAM THIRUVAN...

Sargam Food	5000.0	Sargam Food, Ground floor, Bilkha plaza, Kastu...

Apna Sweets	5000.0	Apna Sweets, 37/7, Sethi Nagar, Ujjain, Madhya...
